# OpenTelemetry Metrics Collector ConfigMap file
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  labels:
    app: otel-collector
data:
  config.yaml: |
    extensions:
      basicauth/grafana:
        client_auth:
          username: "${env:GRAFANA_INSTANCE_ID}"
          password: "${env:GRAFANA_API_KEY}"

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      filelog:
        include: [/var/log/pods/*/*/*.log]
        exclude: [/var/log/pods/*/otel-collector/*.log]
        start_at: end
        include_file_path: true
        include_file_name: false
        operators:
        - type: container

    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 200
        spike_limit_mib: 50

      transform:
        error_mode: ignore
        log_statements:
          - context: log
            statements:
              - set(cache, ExtractPatterns(body, "traceId=(?P<t>[a-f0-9]+),spanId=(?P<s>[a-f0-9]+)"))
              - set(trace_id.string, cache["t"])
              - set(span_id.string, cache["s"])
      
      batch:
        timeout: 10s
        send_batch_size: 1024

    exporters:
      otlphttp/grafana:
        endpoint: "${env:GRAFANA_OTLP_ENDPOINT}"
        auth:
          authenticator: basicauth/grafana

    service:
      extensions: [basicauth/grafana]
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp/grafana]
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp/grafana]
        logs:
          receivers: [otlp, filelog]
          processors: [memory_limiter, transform, batch]
          exporters: [otlphttp/grafana]