# OpenTelemetry Metrics Collector ConfigMap file
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  labels:
    app: otel-collector
data:
  config.yaml: |
    extensions:
      basicauth/grafana:
        client_auth:
          username: "${env:GRAFANA_INSTANCE_ID}"
          password: "${env:GRAFANA_API_KEY}"

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 150
        spike_limit_mib: 30
      
      batch:
        timeout: 10s
        send_batch_size: 1024

    exporters:
      otlphttp/grafana:
        endpoint: "${env:GRAFANA_OTLP_ENDPOINT}"
        auth:
          authenticator: basicauth/grafana

    service:
      extensions: [basicauth/grafana]
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp/grafana]