apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-workload-apps
  namespace: argocd
spec:
  project: gitops
  source:
    repoURL: 'git@github.com:ddolkwak/observability-platform-cluster-desired-state.git'
    targetRevision: HEAD
    path: apps/workloads
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true