apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: priority-class
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: gitops
  source:
    repoURL: 'git@github.com:ddolkwak/observability-platform-cluster-desired-state.git'
    path: manifests/infra/priority-class/base
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true