---
# ServiceAccount File for Kube State Metrics
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-metrics-sa
  namespace: otel-system
  labels:
    app: kube-state-metrics
---
# ClusterRole File for Kube State Metrics
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state-metrics
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "watch"]
---
# ClusterRoleBinding File for Kube State Metrics
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-state-metrics
subjects:
  - kind: ServiceAccount
    name: kube-state-metrics-sa
    namespace: otel-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-state-metrics
